### ISSUE TITLE
LaTeX Error: Something's wrong--perhaps a missing \item.

### ISSUE THREAD

**Issue by drfurtado** [mps9506/quarto-cv#15] opened 2024-03-06 00:24 UTC
I am using the latest version of `rstudio`, `quarto`, and `quarto-cv`. Any help would be greatly appreciated.

[furtado-cv.log](https://github.com/mps9506/quarto-cv/files/14502966/furtado-cv.log)

But I am still getting the error below:

```
ERROR: 
compilation failed- error
LaTeX Error: Something's wrong--perhaps a missing \item.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
```

**Comment by mps9506** [comment] 2024-03-07 12:16
Hi @drfurtado. Sorry for the problems! Can you provide the output from `quarto check` in the terminal? Also which version of quarto-cv is being used?  2.0.0?
Thanks

**Comment by M1V0** [comment] 2024-09-10 20:16
I'm not the original poster, but I am having the exact same issue. I have the most recent version of quarto-cv and the output of quarto check is:

Quarto 1.5.56
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.2.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.41.0: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.5.56
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Using: TinyTex
      Path: /Users/ivorym/Library/TinyTeX/bin/universal-darwin
      Version: 2023

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.11.1
      Path: /Library/Frameworks/Python.framework/Versions/3.11/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.2.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library
      knitr: 1.43
      rmarkdown: 2.23

[✓] Checking Knitr engine render......OK

**Comment by M1V0** [comment] 2024-09-29 19:44
Hi @mps9506, not sure what's changed but I have it all working again! Maybe it was a dependency or something other than your extension.

**Comment by mps9506** [comment] 2024-10-04 14:35
I am closing this since I haven't been able to reproduce. If it continues to come up, feel free to reopen.

**Closed by mps9506** 2024-10-04 14:35 UTC
